-- CREATE TABLE cities (
--     id SERIAL primary key,
--     city VARCHAR(255) NOT NULL,
--     state VARCHAR(255),
--     population INTEGER,
--     country VARCHAR
-- );
-- INSERT INTO cities (city, country, population) VALUES ('Berlin', 'Germany', 3610156);
-- INSERT INTO cities (city, country, population) VALUES ('Hamburg', 'Germany', 1774242);
-- INSERT INTO cities (city, country, population) VALUES ('Munch', 'Germany', 1450381);
-- INSERT INTO cities (city, country, population) VALUES ('Tokyo', 'Japan', 13617445);
-- INSERT INTO cities (city, country, population) VALUES ('Sydney', 'Australia', 4921000);